spring.application.name=Twin-backend
spring.jpa.hibernate.ddl-auto=create-drop
#postgresql://neondb_owner:npg_VDXTCy83ZoqK@ep-weathered-hat-adhtqcmr-pooler.c-2.us-east-1.aws.neon.tech/parking-twin?sslmode=require&channel_binding=require
spring.datasource.url=jdbc:postgresql://ep-weathered-hat-adhtqcmr-pooler.c-2.us-east-1.aws.neon.tech/parking-twin?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VDXTCy83ZoqK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
